const actionlist = [
{
  lookup: "attack",
  name: "Normal Attack",
  color: "#b0b0b0",
  image: "https://terrarp.com/db/action/attack.png",
  description: "<p><em><b>Base</b><b>Offense</b><b>Attack</b></em></p><p>Perform a basic attack.</p>",
  dice: "1d100 + MR + WR + other bonuses",
  roll: "?r attack <span class='masteryreplace'>MR</span> WR <span class='damagepassivemod'></span># <span class='mnamereplace'>Mastery</span> | Character Name | <span class='thrcode'>Code</span>",
  masteries: "arcanamancy astramancy beast-arts geomancy guard-arts hemomancy hydromancy illusion-magic aeromancy crush-weapons dark-magic martial-arts pierce-weapons pyromancy ranged-weapons shadow-arts slash-weapons",
  category: "normal"
},
{
  lookup: "recover",
  name: "Recover",
  color: "#b0b0b0",
  image: "https://terrarp.com/db/action/recover.png",
  description: "<p><em><b>Base</b><b>Action</b></em></p><p>Recover your HP by 1d20. Double your roll result on a nat-20.</p>",
  dice: "1d20",
  roll: "?r recover # Character Name | <span class='thrcode'>Code</span>",
  masteries: "arcanamancy astramancy beast-arts geomancy guard-arts hemomancy hydromancy illusion-magic aeromancy crush-weapons dark-magic martial-arts pierce-weapons pyromancy ranged-weapons shadow-arts slash-weapons",
  category: "normal"
},
{
  lookup: "rush",
  name: "Rush",
  color: "#b0b0b0",
  image: "https://terrarp.com/db/action/rush.png",
  description: "<p><em><b>Base</b><b>Bonus</b></em></p><p><b>Bonus.</b> Double your total movement count this cycle.</p>",
  dice: "-",
  roll: "-",
  masteries: "arcanamancy astramancy beast-arts geomancy guard-arts hemomancy hydromancy illusion-magic aeromancy crush-weapons dark-magic martial-arts pierce-weapons pyromancy ranged-weapons shadow-arts slash-weapons",
  category: "normal"
},
/*SHARED BA*/
  {
    lookup: "healthy",
    name: "Healthy",
    color: "#272627",
    image: "https://terrarp.com/db/action/healthy.png",
    description: "<p><em><b>Passive</b></em></p><p>You're the picture of health.</p><p><b>Passive.</b> Gain 25 HP.</p>",
    dice: "-",
    roll: "-",
    masteries: "arcanamancy astramancy beast-arts geomancy guard-arts hemomancy hydromancy illusion-magic aeromancy crush-weapons dark-magic martial-arts pierce-weapons pyromancy ranged-weapons shadow-arts slash-weapons",
    category: "passive"
  },
  {
    lookup: "alert",
    name: "Alert",
    color: "#272627",
    image: "https://terrarp.com/db/action/alert.png",
    description: "<p><em><b>Passive</b></em></p><p>Nothing gets past you.</p><p><b>Passive.</b> Gain 10 to all saves.</p>",
    dice: "-",
    roll: "-",
    masteries: "arcanamancy astramancy beast-arts geomancy guard-arts hemomancy hydromancy illusion-magic aeromancy crush-weapons dark-magic martial-arts pierce-weapons pyromancy ranged-weapons shadow-arts slash-weapons",
    category: "passive"
  },
  {
    lookup: "mobile",
    name: "Mobile",
    color: "#272627",
    image: "https://terrarp.com/db/action/mobile.png",
    description: "<p><em><b>Passive</b></em></p><p>You stretched this morning.</p><p><b>Passive.</b> Gain 1 movement.</p>",
    dice: "-",
    roll: "-",
    masteries: "arcanamancy astramancy beast-arts geomancy guard-arts hemomancy hydromancy illusion-magic aeromancy crush-weapons dark-magic martial-arts pierce-weapons pyromancy ranged-weapons shadow-arts slash-weapons",
    category: "passive"
  },
  {
    lookup: "consistent",
    name: "Consistent",
    color: "#d9bb2a",
    image: "https://terrarp.com/db/action/consistent.png",
    description: "<p><em><b>Passive</b><b>Unique</b></em></p><p>You perform reliably. Before performing an attack, buff, or check, you may forgo rolling and take 50 for every d100.</p><p>This passive can only be taken if you do not have an alter mastery and have at least 4 masteries at A-rank.</p>",
    dice: "Use the command, then your action, then manually replace all the rolled d100 with 50.",
    roll: "?r consistent # Character Name",
    masteries: "arcanamancy astramancy beast-arts geomancy guard-arts hemomancy hydromancy illusion-magic aeromancy crush-weapons dark-magic martial-arts pierce-weapons pyromancy ranged-weapons shadow-arts slash-weapons",
    category: "Passive"
  },
  {
    lookup: "risky",
    name: "Risky",
    color: "#d9bb2a",
    image: "https://terrarp.com/db/action/risky.png",
    description: "<p><em><b>Passive</b><b>Unique</b></em></p><p>You live life on the edge. Before performing an attack, buff, heal, or check, you may forgo all non-MR and non-WR bonuses and convert them into extra dice of that type.</p><p>(d20) +1d20 per 13<br>(d100) +1d100 per 50<br>(Critical) 1 extra crit roll per 55 sacrificed</p><p>Conversion leftovers are added as a bonus. Risky dice may explode and trigger nat-1 and nat-100 crits.</p>",
    dice: "Use the command, then convert and roll, then add the mod to your action",
    roll: "?r risky # Character Name",
    masteries: "arcanamancy astramancy beast-arts geomancy guard-arts hemomancy hydromancy illusion-magic aeromancy crush-weapons dark-magic martial-arts pierce-weapons pyromancy ranged-weapons shadow-arts slash-weapons",
    category: "Passive"
  },
  {
    lookup: "auto-assist",
    name: "Auto Assist",
    color: "#d9bb2a",
    image: "https://terrarp.com/db/action/assist-mode.png",
    description: "<p><em><b>Passive</b><b>Bonus</b><b>Unique</b></em></p><p>A helpful game setting for beginners. If you don't have access to your UI, then this represents you recalling all of your past experiences to improve your performance.</p><p><b>Passive.</b> Gain 15 HP<br><b>Bonus Action.</b> +15 to attacks, heals, buffs, checks, contributions, and saves. You lose this bonus action if you use it on a save roll.</p><p>This action takes up <b>3 action slots.</b></p>",
    dice: "Use the command below before your main action",
    roll: "?r baautoassist # Character Name",
    masteries: "arcanamancy astramancy beast-arts geomancy guard-arts hemomancy hydromancy illusion-magic aeromancy crush-weapons dark-magic martial-arts pierce-weapons pyromancy ranged-weapons shadow-arts slash-weapons",
    category: "Passive",
    slotcost: 3
  },
/*DEFENSE MAIN*/
{
  lookup: "counter",
  name: "Counter",
  color: "#da6c41",
  image: "https://terrarp.com/db/action/counter.png",
  description: "<p><em><b>Attack</b><b>Defense</b></em></p><p>Time a counterattack to deal more damage and mitigate damage on yourself or an ally.</p><p>If successful: +20 damage and mitigate 10 damage. Otherwise: +10 damage and no damage mitigation.</p>",
  dice: "1d100 + [20/10] + MR + WR + other bonuses<br><b>Succeed on:</b> 70+ (E), 60+ (D), 50+ (C), 40+ (B), 30+ (A), 20+ (S)",
  roll: "?r counter <span class='masteryreplace'>MR</span> WR <span class='damagepassivemod'></span># <span class='mnamereplace'>Mastery</span> | Character Name | <span class='thrcode'>Code</span>",
  masteries: "arcanamancy astramancy beast-arts geomancy guard-arts hemomancy hydromancy illusion-magic aura hyper-sense metamorph",
  category: "normal",
  pair: "C1"
},
{
  lookup: "ultra-counter",
  name: "Ultra Counter",
  color: "#da6c41",
  image: "https://terrarp.com/db/action/ucounter.png",
  description: "<p><em><b>Attack</b><b>Defense</b><b>Special</b></em></p><p>Time a risky but powerful counterattack to deal more damage and mitigate damage on yourself or an ally.</p><p>If successful: +60 damage and mitigate 20 damage. Otherwise: +30 damage and mitigate 5 damage. Also, gain the <i>Vulnerable State</i>.</p>",
  dice: "1d100 + [60/30] + MR + WR + other bonuses<br><b>Succeed on:</b> 80+ (E), 70+ (D), 60+ (C), 50+ (B), 40+ (A), 30+ (S)",
  roll: "?r ultracounter <span class='masteryreplace'>MR</span> WR <span class='damagepassivemod'></span># <span class='mnamereplace'>Mastery</span> | Character Name | <span class='thrcode'>Code</span>",
  masteries: "arcanamancy astramancy beast-arts geomancy guard-arts hemomancy hydromancy illusion-magic aura hyper-sense metamorph",    category: "normal",
    pair: "C1"
},
{
  lookup: "protect",
  name: "Protect",
  color: "#da6c41",
  image: "https://terrarp.com/db/action/protect.png",
  description: "<p><em><b>Attack</b><b>Defense</b></em></p><p>Perform a protective attack.</p><p>Give an ally within range the <i>Protected State</i> whether or not you attacked.</p>",
  dice: "1d100 + MR + WR + other bonuses",
  roll: "?r protect <span class='masteryreplace'>MR</span> WR <span class='damagepassivemod'></span># <span class='mnamereplace'>Mastery</span> | Character Name | <span class='thrcode'>Code</span>",
  masteries: "arcanamancy astramancy beast-arts geomancy guard-arts hemomancy hydromancy illusion-magic aura hyper-sense metamorph",    category: "normal",
  pair: "P1"
},
{
  lookup: "ultra-protect",
  name: "Ultra Protect",
  color: "#da6c41",
  image: "https://terrarp.com/db/action/uprotect.png",
  description: "<p><em><b>Attack</b><b>Defense</b><b>Special</b></em></p><p>Perform a powerful albeit risky protective attack.</p><p>Give 3 allies within range the <i>Protected State</i> whether or not you attacked. You are vulnerable.</p>",
  dice: "1d100 + MR + WR + other bonuses",
  roll: "?r ultraprotect <span class='masteryreplace'>MR</span> WR <span class='damagepassivemod'></span># <span class='mnamereplace'>Mastery</span> | Character Name | <span class='thrcode'>Code</span>",
  masteries: "arcanamancy astramancy beast-arts geomancy guard-arts hemomancy hydromancy illusion-magic aura hyper-sense metamorph",    category: "normal",
pair: "P1"
},
{
  lookup: "hinder",
  name: "Hinder",
  color: "#da6c41",
  image: "https://terrarp.com/db/action/hinder.png",
  description: "<p><em><b>Attack</b><b>Defense</b></em></p><p>Hinder your enemy.</p><p>Damage your enemy's stability (SP).</p>",
  dice: "1d100 + [15] + MR + WR + other bonuses",
  roll: "?r hinder <span class='masteryreplace'>MR</span> WR <span class='damagepassivemod'></span># <span class='mnamereplace'>Mastery</span> | Character Name | <span class='thrcode'>Code</span>",
  masteries: "arcanamancy astramancy beast-arts geomancy guard-arts hemomancy hydromancy illusion-magic aura hyper-sense metamorph",
  category: "normal",
  pair: "D1"
},
{
  lookup: "ultra-hinder",
  name: "Ultra Hinder",
  color: "#da6c41",
  image: "https://terrarp.com/db/action/uhinder.png",
  description: "<p><em><b>Attack</b><b>Defense</b><b>Special</b></em></p><p>Greatly hinder your enemy.</p><p>Greatly damage your enemy's stability (SP). You are vulnerable.</p>",
  dice: "2d100 + [50] + MR + WR + other bonuses",
  roll: "?r ultrahinder <span class='masteryreplace'>MR</span> WR <span class='damagepassivemod'></span># <span class='mnamereplace'>Mastery</span> | Character Name | <span class='thrcode'>Code</span>",
  masteries: "arcanamancy astramancy beast-arts geomancy guard-arts hemomancy hydromancy illusion-magic aura hyper-sense metamorph",
  category: "normal",
  pair: "D1"
},
/*DEFENSE BA*/
{
  lookup: "taunt",
  name: "Taunt",
  color: "#272627",
  image: "https://terrarp.com/db/action/taunt.png",
  description: "<p><em><b>Free</b><b>Bonus</b><b>Unique</b></em></p><p>Grab the enemy's attention.</p><p><b>Free.</b> When you perform any attack action, you may attempt to taunt your target and multiply your total damage calculation by 3. The result is your Threat Value.</p><p><b>Bonus.</b> Your threat value is multiplied by 5 instead of 3.</p><p><b><u>Take this action for free when you select any [defense] tag action.</u></b></p>",
  dice: "Use the command after your attack, replace damage with your attack roll result",
  roll: "?r taunt DAMAGE # Character Name",
  masteries: "arcanamancy astramancy beast-arts geomancy guard-arts hemomancy hydromancy illusion-magic aura hyper-sense",
  category: "normal",
  slotcost: 0
},
{
  lookup: "torment",
  name: "Torment",
  color: "#272627",
  image: "https://terrarp.com/db/action/dba.png",
  description: "<p><em><b>Free</b><b>Bonus</b></em></p><p>You deal damage just by being near an enemy.</p><p><b>Free.</b> Deal 10 (D) 15 (B) 20 (S) flat damage to an enemy adjacent to you.</p><p><b>(BA) Ultra Torment.</b> Double your Agonize's damage.</p><p><b>(BA) Area Torment.</b> Deal damage to all enemies adjacent to you. When the battle map is not in use, damage all enemies you can narratively see.</p>",
  dice: "Use the command below",
  roll: "?r torment <span class='masteryreplace'>MR</span> # Character Name",
  masteries: "arcanamancy astramancy beast-arts geomancy guard-arts hemomancy hydromancy illusion-magic aura hyper-sense",
  category: "normal"
},
{
  lookup: "alterhinder",
  name: "Alter Hinder",
  color: "#272627",
  image: "https://terrarp.com/db/action/dba.png",
  description: "<p><em><b>Free</b><b>Bonus</b></em></p><p>You have percise control over hindering abilities.</p><p><b>Free.</b> When you use Hinder or Ultra Hinder, distribute your damage as you wish between your target’s HP and SP.</p><p><b>Bonus.</b> When you use Hinder or Ultra Hinder, add 10 (D) 20 (B) 30 (S) bonus damage.</p>",
  dice: "Use the command below",
  roll: "?r alterhinder <span class='masteryreplace'>MR</span> # Character Name",
  masteries: "arcanamancy astramancy beast-arts geomancy guard-arts hemomancy hydromancy illusion-magic aura hyper-sense",
  category: "normal"
},
{
  lookup: "disruptive",
  name: "Disruptive",
  color: "#272627",
  image: "https://terrarp.com/db/action/dba.png",
  description: "<p><em><b>Free</b><b>Bonus</b></em></p><p>Your attacks disrupt enemies.</p><p><b>Free.</b> Deals 10 (D) 20 (B) 30 (S) flat SP damage when you attack.</p><p><b>Bonus.</b> Double your disruptive damage.</p>",
  dice: "Use the command below",
  roll: "?r disruptive <span class='masteryreplace'>MR</span> # Character Name",
  masteries: "arcanamancy astramancy beast-arts geomancy guard-arts hemomancy hydromancy illusion-magic aura hyper-sense aeromancy crush-weapons dark-magic martial-arts pierce-weapons pyromancy ranged-weapons shadow-arts slash-weapons battle-spirits dynamism evoke weapon-arts corrupt",
  category: "normal"
},
{
  lookup: "shield",
  name: "Shield",
  color: "#272627",
  image: "https://terrarp.com/db/action/dba.png",
  description: "<p><em><b>Bonus</b></em></p><p>Your defensive abilities provide shielding.</p><p><b>Bonus.</b> Grant the target of your [defense] action (self and/or allies) 5 (D) 10 (B) 15 (S) damage mitigation. If Ultra Protect was used, you may distribute the mitigation in multiple of 5s.</p>",
  dice: "Use the command below",
  roll: "?r bashield <span class='masteryreplace'>MR</span> # Character Name",
  masteries: "arcanamancy astramancy beast-arts geomancy guard-arts hemomancy hydromancy illusion-magic aura hyper-sense",
  category: "normal"
},
{
  lookup: "overload",
  name: "Overload",
  color: "#272627",
  image: "https://terrarp.com/db/action/dba.png",
  description: "<p><em><b>Bonus</b></em></p><p>Overload your abilities and shutdown briefly afterwards, or stand in place to overcharge your abilities.</p><p><b>Bonus.</b> Your attacks and buffs gain a 20 (D) 30 (B) 40 (S) bonus. Heals gain a 10 (D) 15 (B) 20 (S) bonus.</p><p>You cannot move this cycle. If a battle map is not used, roll ALL your saves with Disadvantage in the next damage phase.</p>",
  dice: "Use the command below before your main action",
  roll: "?r baoverload <span class='masteryreplace'>MR</span> # Character Name",
  masteries: "arcanamancy astramancy beast-arts geomancy guard-arts hemomancy hydromancy illusion-magic aura hyper-sense aeromancy crush-weapons dark-magic martial-arts pierce-weapons pyromancy ranged-weapons shadow-arts slash-weapons battle-spirits dynamism evoke weapon-arts corrupt",
  category: "normal"
},
/*OFFENSE*/
{
  lookup: "stable",
  name: "Stable Attack",
  color: "#c72828",
  image: "https://terrarp.com/db/action/stable.png",
  description: "<p><em><b>Offense</b><b>Attack</b></em></p><p>Perform a rudimentary and reliable attack.</p><p>This attack uses d20s instead of d100</p>",
  dice: "6d20 + MR + WR + other bonuses<br><b>Explosion:</b> Each 19/20 = +1d20",
  roll: "?r stable <span class='masteryreplace'>MR</span> WR <span class='damagepassivemod'></span># <span class='mnamereplace'>Mastery</span> | Character Name | <span class='thrcode'>Code</span>",
  masteries: "aeromancy crush-weapons dark-magic martial-arts pierce-weapons pyromancy ranged-weapons shadow-arts slash-weapons battle-spirits dynamism evoke weapon-arts corrupt",
  category: "normal",
  pair: "S1"
},
{
  lookup: "burst",
  name: "Burst Attack",
  color: "#c72828",
  image: "https://terrarp.com/db/action/burst.png",
  description: "<p><em><b>Offense</b><b>Attack</b><b>Special</b></em></p><p>Perform a risky explosive attack.</p><p>Roll 10d20 and add a d20 for each mastery and weapon rank (max: 20d20). You are vulnerable.</p>",
  dice: "10d20 + 1d20 per MR + 1d20 per WR + other bonuses<br><b>Explosion:</b> Each 19/20 = +1d20",
  roll: "?r burst <span class='masteryreplace'>MR</span> WR <span class='damagepassivemod'></span># <span class='mnamereplace'>Mastery</span> | Character Name | <span class='thrcode'>Code</span>",
  masteries: "aeromancy crush-weapons dark-magic martial-arts pierce-weapons pyromancy ranged-weapons shadow-arts slash-weapons battle-spirits dynamism evoke weapon-arts corrupt",
  category: "normal",
  pair: "S1"
},
{
  lookup: "sharp",
  name: "Sharp Attack",
  color: "#c72828",
  image: "https://terrarp.com/db/action/sharp.png",
  description: "<p><em><b>Offense</b><b>Attack</b></em></p><p>Perform a refined attack.</p><p>This strike doubles MR and increases WR by 50%.</p>",
  dice: "1d100 + (MR * 2) + (WR * 1.5) + other bonuses",
  roll: "?r sharp <span class='masteryreplace'>MR</span> WR <span class='damagepassivemod'></span># <span class='mnamereplace'>Mastery</span> | Character Name | <span class='thrcode'>Code</span>",
  masteries: "aeromancy crush-weapons dark-magic martial-arts pierce-weapons pyromancy ranged-weapons shadow-arts slash-weapons battle-spirits dynamism evoke weapon-arts corrupt",
  category: "normal",
  pair: "M1"
},
{
  lookup: "multi",
  name: "Multi Attack",
  color: "#c72828",
  image: "https://terrarp.com/db/action/multi.png",
  description: "<p><em><b>Offense</b><b>Attack</b><b>Special</b></em></p><p>Perform a maneuver that strikes twice.</p><p>Each strike applies MR and WR at full value and increases other bonuses by an extra 50%. Gain the <i>Vulnerable State</i>.</p>",
  dice: "2d100 + (MR * 2) + (WR * 2) + (other bonuses * 1.5)",
  roll: "?r multi <span class='masteryreplace'>MR</span> WR <span class='damagepassivemod'></span># <span class='mnamereplace'>Mastery</span> | Character Name | <span class='thrcode'>Code</span>",
  masteries: "aeromancy crush-weapons dark-magic martial-arts pierce-weapons pyromancy ranged-weapons shadow-arts slash-weapons battle-spirits dynamism evoke weapon-arts corrupt",
  category: "normal",
  pair: "M1"
},
{
  lookup: "sneak",
  name: "Sneak Attack",
  color: "#c72828",
  image: "https://terrarp.com/db/action/sneak.png",
  description: "<p><em><b>Offense</b><b>Attack</b></em></p><p>Perform a sneak attack.</p><p>If successful, gain 40 extra damage. Otherwise, gain 20 damage.</p>",
  dice: "1d100 + [40/20] + MR + WR + other bonuses<br><b>Succeed on:</b> 75+ (E), 65+ (D), 55+ (C), 45+ (B), 35+ (A), 25+ (S)",
  roll: "?r sneak <span class='masteryreplace'>MR</span> WR <span class='damagepassivemod'></span># <span class='mnamereplace'>Mastery</span> | Character Name | <span class='thrcode'>Code</span>",
  masteries: "aeromancy crush-weapons dark-magic martial-arts pierce-weapons pyromancy ranged-weapons shadow-arts slash-weapons battle-spirits dynamism evoke weapon-arts corrupt",
  category: "normal",
  pair: "T1"
},
{
  lookup: "critical",
  name: "Critical Attack",
  color: "#c72828",
  image: "https://terrarp.com/db/action/critical.png",
  description: "<p><em><b>Offense</b><b>Attack</b><b>Special</b></em></p><p>Perform a risky attack with advantage and an expanded critical range.</p><p>If successful, triple your total damage. Gain the <i>Vulnerable State</i>.</p><p><b>If you have advantage, roll this action once and then roll it again, but change the ?r critical to ?r critical2</b></p>",
  dice: "1d100 (adv) + [40] + MR + WR + other bonuses<br><b>Succeed on:</b> 95+ (E), 93+ (D), 91+ (C), 89+ (B), 87+ (A), 85+ (S)",
  roll: "?r critical <span class='masteryreplace'>MR</span> WR <span class='damagepassivemod'></span># <span class='mnamereplace'>Mastery</span> | Character Name | <span class='thrcode'>Code</span>",
  masteries: "aeromancy crush-weapons dark-magic martial-arts pierce-weapons pyromancy ranged-weapons shadow-arts slash-weapons battle-spirits dynamism evoke weapon-arts corrupt",
  category: "normal",
  pair: "T1"
},
{
  lookup: "wild",
  name: "Wild Attack",
  color: "#c72828",
  image: "https://terrarp.com/db/action/wild.png",
  description: "<p><em><b>Offense</b><b>Attack</b></em></p><p>Make a bombastically unrefined attack.</p><p>Roll 2d100 and count only weapon ranks.</p>",
  dice: "2d100 + WR + other bonuses",
  roll: "?r wild <span class='masteryreplace'>MR</span> WR <span class='damagepassivemod'></span># <span class='mnamereplace'>Mastery</span> | Character Name | <span class='thrcode'>Code</span>",
  masteries: "aeromancy crush-weapons dark-magic martial-arts pierce-weapons pyromancy ranged-weapons shadow-arts slash-weapons battle-spirits dynamism evoke weapon-arts corrupt",
  category: "normal",
  pair: "R1"
},
{
  lookup: "reckless",
  name: "Reckless Attack",
  color: "#c72828",
  image: "https://terrarp.com/db/action/reckless.png",
  description: "<p><em><b>Offense</b><b>Attack</b><b>Special</b></em></p><p>Perform a high-risk chaotically turbulent attack.</p><p>Nat-100 or Nat1+100 = damage * 2. Nat-200 (100,100), damage * 7. Gain the <i>Vulnerable State</i>.</p>",
  dice: "3d100 + MR + WR + other bonuses (4d100 at A and S)",
  roll: "?r reckless <span class='masteryreplace'>MR</span> WR <span class='damagepassivemod'></span># <span class='mnamereplace'>Mastery</span> | Character Name | <span class='thrcode'>Code</span>",
  masteries: "aeromancy crush-weapons dark-magic martial-arts pierce-weapons pyromancy ranged-weapons shadow-arts slash-weapons battle-spirits dynamism evoke weapon-arts corrupt",
  category: "normal",
  pair: "R1"
},
/*OFFENSIVE BA*/
  {
    lookup: "area-effect",
    name: "Area Effect",
    color: "#272627",
    image: "https://terrarp.com/db/action/oba.png",
    description: "<p><em><b>Free</b><b>Bonus</b></em></p><p>Your attacks affects an area</p><p><b>Free.</b> Distribute your damage in any amount to the targeted enemy and any other enemies adjacent to them. Take retaliation (if any) from each enemy you attack this way.</p><p><b>Bonus.</b> Deal 1d20 (D) 2d20 (B) 3d20 (S) flat Damage to the targeted enemy and all other enemies adjacent to them. This BA does not trigger retaliation damage.</p><p>When the battle map is not in use, you may target any enemies that are narrative close to one another.</p>",
    dice: "Use the command below",
    roll: "?r areaeffect <span class='masteryreplace'>MR</span> # Character Name",
    masteries: "aeromancy crush-weapons dark-magic martial-arts pierce-weapons pyromancy ranged-weapons shadow-arts slash-weapons battle-spirits dynamism evoke weapon-arts corrupt",
    category: "normal",
  },
  {
    lookup: "duelist",
    name: "Duelist",
    color: "#272627",
    image: "https://terrarp.com/db/action/oba.png",
    description: "<p><em><b>Bonus</b></em></p><p>You deal more damage up close.</p><p><b>Bonus.</b> If you attack an enemy in melee (while on their square, or an adjacent square if they are oversized), your attack gains 20 (D) 30 (B) 40 (S) extra damage.</p>",
    dice: "Use the command below before your main action",
    roll: "?r baduelist <span class='masteryreplace'>MR</span> # Character Name",
    masteries: "aeromancy crush-weapons dark-magic martial-arts pierce-weapons pyromancy ranged-weapons shadow-arts slash-weapons battle-spirits dynamism evoke weapon-arts corrupt",
    category: "normal",
  },
  {
    lookup: "sharpshooter",
    name: "Sharpshooter",
    color: "#272627",
    image: "https://terrarp.com/db/action/oba.png",
    description: "<p><em><b>Free</b><b>Bonus</b></em></p><p>You deal more damage at range.</p><p>When you attack an enemy while not on their square (or 2 squares away when they are oversized), you may use the following:</p><p><b>Free.</b> Your attack gains 5 extra damage (10 if you have Hyper Awareness).</p><p><b>Bonus.</b> Your attack gains 15 (D) 20 (B) 25 (S) extra damage in addition to the bonus above.</p>",
    dice: "Use the command below before your main action",
    roll: "?r sharpshooter <span class='masteryreplace'>MR</span> # Character Name",
    masteries: "aeromancy crush-weapons dark-magic martial-arts pierce-weapons pyromancy ranged-weapons shadow-arts slash-weapons battle-spirits dynamism evoke weapon-arts corrupt",
    category: "normal",
  },
/*SUPPORT ACTIONS*/
{
	lookup: "heal",
	name: "Heal",
	color: "#3460d0",
	image: "https://terrarp.com/db/action/heal.png",
  description: "<p><em><b>Action</b><b>Support</b></em></p><p>Heal yourself or allies.</p><p>This action uses d20s instead of d100.</p><p><b>Click one of the toggles below:</b></p><p span class='single' onclick='targetReplaceSingle(this)'><b>(Single) </b>Heal 1 target for the full amount</p><p span class='aoe' onclick='targetReplaceAOE(this)'><b>(AoE) </b>Split your heal evenly among 3 targets</p>",
	dice: "2d20 + MR + WR + other bonuses then divide by 3 if AoE<br><b>Explosion:</b> +1d20 per 20 rolled",
	roll: "?r heal <span class='masteryreplace'>MR</span> WR <span class='supportpassivemod'></span># <span class='targetreplace'></span><span class='mnamereplace'>Mastery</span> | Character Name | <span class='thrcode'>Code</span>",
	masteries: "alchemy animancy chronomancy divine-magic harmonic-magic magitech nature-magic spirit-magic mend summon",
	category: "normal",
	pair: "H1"
},
{
	lookup: "power-heal",
	name: "Power Heal",
	color: "#3460d0",
	image: "https://terrarp.com/db/action/pheal.png",
  description: "<p><em><b>Action</b><b>Support</b><b>Special</b></em></p><p>Heal yourself or allies.</p><p>This action uses d20s instead of d100. Gain the <i>Vulnerable State</i></p><p><b>Click one of the toggles below:</b></p><p span class='single' onclick='targetReplaceSingle(this)'><b>(Single) </b>Heal 1 target for the full amount</p><p span class='aoe' onclick='targetReplaceAOE(this)'><b>(AoE) </b>Split your heal evenly among 3 targets</p>",
	dice: "4d20 + MR + WR + other bonuses then divide by 3 if AoE<br><b>Explosion:</b> +1d20 per 20 rolled",
	roll: "?r powerheal <span class='masteryreplace'>MR</span> WR <span class='supportpassivemod'></span># <span class='targetreplace'></span><span class='mnamereplace'>Mastery</span> | Character Name | <span class='thrcode'>Code</span>",
  masteries: "alchemy animancy chronomancy divine-magic harmonic-magic magitech nature-magic spirit-magic mend summon",
	category: "normal",
	pair: "H1"
},
{
	lookup: "buff",
	name: "Buff",
	color: "#3460d0",
	image: "https://terrarp.com/db/action/buff.png",
  description: "<p><em><b>Action</b><b>Support</b></em></p><p>Give yourself and allies a damage buff.</p><p><b>Click one of the toggles below:</b></p><p span class='single' onclick='targetReplaceSingle(this)'><b>(Single) </b>Give one target a damage buff that lasts 3 posts</p><p span class='aoe' onclick='targetReplaceAOE(this)'><b>(AoE) </b>Give three targets a damage buff that lasts for 1 post.</p>",
	dice: "2d100 + [30] + MR + WR + other bonuses then divide by 3",
	roll: "?r buff <span class='masteryreplace'>MR</span> WR <span class='supportpassivemod'></span># <span class='targetreplace'></span><span class='mnamereplace'>Mastery</span> | Character Name | <span class='thrcode'>Code</span>",
  masteries: "alchemy animancy chronomancy divine-magic harmonic-magic magitech nature-magic spirit-magic mend summon",
	category: "normal",
	pair: "B1"
},
{
	lookup: "power-buff",
	name: "Power Buff",
	color: "#3460d0",
	image: "https://terrarp.com/db/action/pbuff.png",
  description: "<p><em><b>Action</b><b>Support</b><b>Special</b></em></p><p>Give yourself and allies a powerful damage buff. Gain the <i>vulnerable state</i>.</p><p><b>Click one of the toggles below:</b></p><p span class='single' onclick='targetReplaceSingle(this)'><b>(Single) </b>Give one target a damage buff that lasts 3 posts</p><p span class='aoe' onclick='targetReplaceAOE(this)'><b>(AoE) </b>Give three targets a damage buff that lasts for 1 post.</p>",
	dice: "2d100 + [75] + MR + WR + other bonuses then divide by 3",
	roll: "?r powerbuff <span class='masteryreplace'>MR</span> WR <span class='supportpassivemod'></span># <span class='targetreplace'></span><span class='mnamereplace'>Mastery</span> | Character Name | <span class='thrcode'>Code</span>",
  masteries: "alchemy animancy chronomancy divine-magic harmonic-magic magitech nature-magic spirit-magic mend summon",
	category: "normal",
	pair: "B1"
},
{
	lookup: "inspire",
	name: "Inspire",
	color: "#3460d0",
	image: "https://terrarp.com/db/action/inspire.png",
  description: "<p><em><b>Action</b><b>Support</b></em></p><p>Inspire yourself and allies.</p><p>Give 3 targets (self and/or allies) a 1d6 + (1d6 per MR) bonus to: checks, contribution, saves, buffs, or heals.</p>",
	dice: "1d6 + 1d6 per MR",
	roll: "?r inspire <span class='masteryreplace'>MR</span> <span class='inspirepassivemod'></span># <span class='mnamereplace'>Mastery</span> | Character Name | <span class='thrcode'>Code</span>",
  masteries: "alchemy animancy chronomancy divine-magic harmonic-magic magitech nature-magic spirit-magic mend summon",
	category: "normal",
	pair: "I1"
},
{
	lookup: "haste",
	name: "Haste",
	color: "#3460d0",
	image: "https://terrarp.com/db/action/haste.png",
  description: "<p><em><b>Action</b><b>Support</b></em></p><p>Increase yours and allies’ speed.</p><p>Roll 1d6+2 and distribute the movement between up to 3 targets (self and/or allies). The bonus movement lasts 1 cycle. Haste may stack with boost and itself.</p>",
	dice: "1d6 + 2",
  roll: "?r haste # Character Name | <span class='thrcode'>Code</span>",
  masteries: "alchemy animancy chronomancy divine-magic harmonic-magic magitech nature-magic spirit-magic mend summon",
	category: "normal",
	pair: "I1"
},
/*SUPPORT BA*/
{
  lookup: "revive",
  name: "Revive",
  color: "#272627",
  image: "https://terrarp.com/db/action/sba.png",
  description: "<p><em><b>Bonus</b></em></p><p>When you target a dead ally with heal, buff, haste, or inspire, revive them at 50% HP and give them that action’s effect. If AoE was used, pick 1 of the targeted allies.</p><p><b><u>Take this action for free when you select any [support] tag action.</u></b></p>",
  dice: "Use the command below",
  roll: "?r revive # Character Name",
  masteries: "alchemy animancy chronomancy divine-magic harmonic-magic magitech nature-magic spirit-magic mend summon",
	category: "normal",
  slotcost: 0
},
{
	lookup: "overheal",
	name: "Overheal",
	color: "#272627",
	image: "https://terrarp.com/db/action/sba.png",
  description: "<p><em><b>Passive</b></em></p><p>You can heal and be healed above the max HP.</p><p><b>Passive.</b> When you heal or are healed, you may go above the target's max HP by 20 (D) 30 (B) 40 (S) HP. Overheal applies to all effects that recover HP.</p>",
  dice: "Use the command below",
  roll: "?r overheal <span class='masteryreplace'>MR</span> # Character Name",
  masteries: "alchemy animancy chronomancy divine-magic harmonic-magic magitech nature-magic spirit-magic mend summon",
	category: "normal",
},
{
	lookup: "versatile",
	name: "Versatile",
	color: "#272627",
	image: "https://terrarp.com/db/action/sba.png",
  description: "<p><em><b>Free</b><b>Bonus</b></em></p><p>You are versatile. When you perform an AoE Heal/Power Heal or Buff/Power Buff (and have both actions equipped), you may:</p><p><b>Free.</b> Apply the effects to 2 targets (self and/or allies) and the last heal/buff amount to one of them.</p><p><b>Bonus Action.</b> Roll both actions and choose if each target gets a heal or buff. If you have a bonus from Inspire or Coordinate, apply it to both actions.</p>",
	dice: "Use the command below before your main action",
  roll: "?r versatile # Character Name",
  masteries: "alchemy animancy chronomancy divine-magic harmonic-magic magitech nature-magic spirit-magic mend summon",
	category: "normal",
},
{
	lookup: "cure",
	name: "Cure",
	color: "#272627",
	image: "https://terrarp.com/db/action/sba.png",
  description: "<p><em><b>Bonus</b></em></p><p>Cure yourself or others of their ailments.</p><p><b>Bonus.</b> When you use Heal/Power Heal or Buff/Power Buff, you may remove 1d4+2 curable conditions from your targets (self and/or allies). If AoE was used, distribute the cure charges in any amount between up to 3 targets (self and/or allies).</p>",
	dice: "Post the code below before or after your Buff / Power Buff roll.",
  roll: "?r bacure # Character Name",
  masteries: "alchemy animancy chronomancy divine-magic harmonic-magic magitech nature-magic spirit-magic mend summon",
	category: "normal",
},
{
	lookup: "boost",
	name: "Boost",
	color: "#272627",
	image: "https://terrarp.com/db/action/sba.png",
  description: "<p><em><b>Bonus</b></em></p><p>Grant others a small movement boost.</p><p><b>Bonus.</b> When you target an ally with any action, grant them 2 extra movements. If AoE was used, pick 1 of the targeted allies.</p>",
  dice: "Use the command below",
  roll: "?r baboost # Character Name",
  masteries: "alchemy animancy chronomancy divine-magic harmonic-magic magitech nature-magic spirit-magic mend summon",
	category: "normal",
},
  /*ALTER PBA*/
    {
      lookup: "defense",
      name: "Defense",
      color: "#54299b",
      image: "https://terrarp.com/db/action/defense.png",
      description: "<p><em><b>Passive</b></em></p><p>You are more resilient to damage and pain.</p><p><b>Passive.</b> Your maximum HP increases by 10 per mastery rank.</p>",
      dice: "-",
      roll: "-",
      masteries: "aura hyper-sense metamorph",
      category: "passive"
    },
    {
      lookup: "damage",
      name: "Damage",
      color: "#54299b",
      image: "https://terrarp.com/db/action/damage.png",
      description: "<p><em><b>Passive</b></em></p><p>Your combat abilities are greatly empowered.</p><p><b>Passive.</b> All attack actions gain +5 bonus damage per mastery rank.</p>",
      dice: "-",
      roll: "-",
      masteries: "battle-spirits corrupt evoke metamorph weapon-arts",
      category: "passive"
    },
    {
      lookup: "support",
      name: "Support",
      color: "#54299b",
      image: "https://terrarp.com/db/action/support.png",
      description: "<p><em><b>Passive</b></em></p><p>Your supportive abilities are more powerful.</p><p><b>Passive.</b> All heal and buff actions gain a +5 bonus per mastery rank.</p>",
      dice: "-",
      roll: "-",
      masteries: "corrupt mend summon weapon-arts",
      category: "passive"
    },
    {
      lookup: "speed",
      name: "Speed",
      color: "#54299b",
      image: "https://terrarp.com/db/action/speed.png",
      description: "<p><em><b>Passive</b></em></p><p>You are incredibly fast.</p><p><b>Passive.</b> Gain the following stacking effects: +1 movement (D), +5 reflex (C), +1 movement (B), +5 reflex (A), +1 movement (S).</p><p>Total effects gained at S-rank: +3 movements and +10 reflex.</p>",
      dice: "-",
      roll: "-",
      masteries: "battle-spirits dynamism",
      category: "passive"
    },
    {
      lookup: "extension",
      name: "Extension",
      color: "#54299b",
      image: "https://terrarp.com/db/action/extension.png",
      description: "<p><em><b>Passive</b><b>Bonus</b></em></p><p>You have extended range.</p><p><b>Passive.</b> +1 range.</p><p><b>Bonus.</b> +2 range instead of +1 this cycle.</p>",
      dice: "Use the command below",
      roll: "?r baextension # Character Name",
      masteries: "hyper-sense evoke summon",
      category: "normal"
    },
    {
      lookup: "hyper-awareness",
      name: "Hyper Awareness",
      color: "#54299b",
      description: "<p><em><b>Passive</b><b>Bonus</b></em></p><p>You have incredibly high perception.</p><p><b>Passive.</b> Whenever you make an Awareness check, make it with advantage.</p><p><b>Bonus.</b> Your attacks and buffs gain 10 (D) 15 (B) 20 (S) bonus damage and heals gain a 5 (D) 10 (B) 15 (S) bonus per square of distance, starting from the square adjacent to you and ending on the target's.</p>",
      dice: "Use the command below",
      roll: "?r bahyperawareness <span class='masteryreplace'>MR</span> # <span class='mnamereplace'>Mastery</span> | Character Name",
      masteries: "hyper-sense",
      category: "normal"
    },
    {
      lookup: "momentum",
      name: "Momentum",
      color: "#54299b",
      image: "https://terrarp.com/db/action/momentum.png",
      description: "<p><em><b>Passive</b><b>Free</b></em></p><p>Your attack damage is amplified by momentum.</p><p><b>Passive.</b> +1 movement</p><p><b>Free.</b> Gain 5 extra damage per movement you have this cycle (used or unused), maximum: +75.</p>",
      dice: "Use the command below before your main action",
      roll: "?r momentum TOTALMOVEMENT # Dynamism | Character Name",
      masteries: "dynamism",
      category: "passive"
    },
    {
      lookup: "rover",
      name: "Rover",
      color: "#54299b",
      image: "https://terrarp.com/db/action/rover.png",
      description: "<p><em><b>Passive</b><b>Bonus</b></em></p><p>You move efficiently.</p><p><b>Passive.</b> All damage resulting from moving is halved.</p><p><b>Bonus.</b> You may split your movements, allowing you to move → act → move.</p>",
      dice: "Use the command below",
      roll: "?r rover # Dynamism | Character Name",
      masteries: "dynamism",
      category: "normal"
    },
    {
      lookup: "maneuver",
      name: "Maneuver",
      color: "#54299b",
      image: "https://terrarp.com/db/action/maneuver.png",
      description: "<p><em><b>Passive</b><b>Bonus</b></em></p><p>Your various morphs grant you some speed and the ability to overcome all obstacles.</p><p><b>Passive.</b> +1 movement</p><p><b>Bonus.</b> Ignore difficult terrain and all movement-based damage this cycle.</p>",
      dice: "Use the command below",
      roll: "?r bamaneuver # Metamoprh | Character Name",
      masteries: "metamorph",
      category: "normal"
    },
    {
      lookup: "regeneration",
      name: "Regeneration",
      color: "#54299b",
      image: "https://terrarp.com/db/action/regeneration.png",
      description: "<p><em><b>Free</b><b>Bonus</b></em></p><p>Your mastery grants you passive healing.</p><p><b>Free.</b> Regain 1d6 (D) 2d6 (B) 3d6 (S) HP every cycle. Twice allows you to double the dice roll.</p><p><b>Bonus.</b> Regain the rolled HP and grant an ally the same amount, or forgo your own regeneration and grant an ally double the rolled HP.</p>",
      dice: "Use the command below",
      roll: "?r regeneration <span class='masteryreplace'>MR</span> # <span class='mnamereplace'>Mastery</span> | Character Name",
      masteries: "mend",
      category: "normal"
    },
    {
      lookup: "infuse",
      name: "Infuse",
      color: "#54299b",
      image: "https://terrarp.com/db/action/infuse.png",
      description: "<p><em><b>Free</b><b>Bonus</b></em></p><p>Your actions provide healing.</p><p><b>Free.</b> When you target an ally or allies with Renegeration, a [support] tag, or a [defense] tag action, heal them for 5 (D) 10 (B) 15 (S) HP. If AoE was used, distribute the heal in any amount between up to 3 targets in multiple of 5s.</p>",
      dice: "Use the command below",
      roll: "?r infuse <span class='masteryreplace'>MR</span> # <span class='mnamereplace'>Mastery</span> | Character Name",
      masteries: "mend",
      category: "normal"
    },
    {
      lookup: "coordinate",
      name: "Coordinate",
      color: "#54299b",
      image: "https://terrarp.com/db/action/coordinate.png",
      description: "<p><em><b>Bonus</b></em></p><p>Command your summon(s) to assist you and your allies.</p><p><p><b>Bonus.</b> Both you and an ally gain a +5 (D) +15 (B) +25 (S) flat bonus to attack, heal, or buff actions this cycle.</p>",
      dice: "Use the command below",
      roll: "?r bacoordinate <span class='masteryreplace'>MR</span> # <span class='mnamereplace'>Mastery</span> | Character Name",
      masteries: "summon",
      category: "normal"
    },
  {
      lookup: "guardian",
      name: "Guardian",
      color: "#54299b",
      image: "https://terrarp.com/db/action/guardian.png",
      description: "<p><em><b>Free</b></em></p><p>Your aura mitigates damage.</p><p><b>Free.</b> Grant the target of your action or bonus action (self and/or allies) 5 (D) 10 (B) 15 (S) damage mitigation. If AoE was used, distribute the heal in any amount between up to 3 targets in multiple of 5s.</p>",
      dice: "Use the command below",
      roll: "?r guardian <span class='masteryreplace'>MR</span> # <span class='mnamereplace'>Mastery</span> | Character Name",
      masteries: "aura",
      category: "normal"
    },
    {
      lookup: "savior",
      name: "Savior",
      color: "#54299b",
      image: "https://terrarp.com/db/action/savior.png",
      description: "<p><em><b>Bonus</b></em></p><p>Your aura protects others from harm.</p><p><p><b>Bonus.</b> Your aura keeps you and your allies safe. Give 3 targets within range +5 (D) +15 (B) +25 (S) to a save roll next cycle. You may also target yourself. Savior may not stack.</p>",
      dice: "Use the command below before your main action",
      roll: "?r basavior <span class='masteryreplace'>MR</span> # <span class='mnamereplace'>Mastery</span> | Character Name",
      masteries: "aura",
      category: "normal"
    },
    {
      lookup: "berserk",
      name: "Berserk",
      color: "#54299b",
      image: "https://terrarp.com/db/action/berserk.png",
      description: "<p><em><b>Bonus</b></em></p><p>Your abilities become stronger when you take damage.</p><p><b>Bonus.</b> Gain a bonus to attacks, heals, and buffs based on the amount of HP lost in the last damage phase and from this cycle's retaliation damage after all heals and damage reduction. This bonus is counted up to a maximum per rank: 20 (D) 40 (B) 60 (S).</p>",
      dice: "Use the command below before your main action",
      roll: "?r baberserk <span class='masteryreplace'>MR</span> # <span class='mnamereplace'>Mastery</span> | Character Name",
      masteries: "battle-spirits",
      category: "normal"
    },
    {
      lookup: "corruption",
      name: "Corruption",
      color: "#54299b",
      image: "https://terrarp.com/db/action/corruption.png",
      description: "<p><em><b>Passive</b><b>Bonus</b></em></p><p>Your corruption grants you power in exchange for your well-being.</p><p><b>Passive.</b> Lose 1d20 (D) 2d20 (B) 3d20 (S) flat HP when you post and gain the same amount as an extra modifier for attacks, buffs, or heals. Checks gain half the amount. This process repeats each cycle. If the roll result is even, you do not lose HP.</p><p><b>Bonus.</b> Suppress the health cost.</p>",
      dice: "Use the command below before your main action",
      roll: "?r corruption <span class='masteryreplace'>MR</span> # <span class='mnamereplace'>Mastery</span> | Character Name",
      masteries: "corrupt",
      category: "normal"
    },
    {
      lookup: "exceed",
      name: "Exceed",
      color: "#54299b",
      image: "https://terrarp.com/db/action/exceed.png",
      description: "<p><em><b>Bonus</b></em></p><p>Surpass your limits at your own peril.</p><p><b>Bonus.</b> After rolling your action, you may damage yourself and gain an effect. Choose one from the following list:</p><p><b>[-10 HP]</b> +20 to attacks, heals, or buffs<br><b>[-25 HP]</b> Advantage to 1 save<br><b>[-50 HP]</b> Gain Advantage on an attack, heal, or buff (crit gains an extra d100)<br><b>[-100 HP]</b> You may perform an additional non-special action.</p>",
      dice: "Use the command below",
      roll: "?r baexceed<span class='exceedvalue'>10</span> # Evoke | Character Name",
      masteries: "evoke",
      category: "normal"
    },
    {
      lookup: "charge",
      name: "Charge",
      color: "#54299b",
      image: "https://terrarp.com/db/action/charge.png",
      description: "<p><em><b>Free</b><b>Bonus</b></em></p><p>Your weapon is charged with power.</p><p><b>Free.</b> Add a 5 (D) 15 (B) 25 (S) bonus to a pool at the start of your turn. This charge activates when it reaches 75 or higher regardless of what action you do that cycle.</p><p><b>(BA) Unload.</b> (74 or lower) Gain the charged amount as a bonus</p><p><b>(BA) Hold</b> (75 or higher) Stop the charge from unloading</p>",
      dice: "Use the command below before your main action",
      roll: "?r charge <span class='masteryreplace'>MR</span> - CHARGEAMOUNT # <span class='mnamereplace'>Mastery</span> | Character Name",
      masteries: "weapon-arts",
      category: "normal"
    },
];

// Make available globally
window.actionlist = actionlist;
