const masterylist = [
  {
    id: 1,
    lookup: "arcanamancy",
    name: "Arcanamancy",
    color: "#50cbe3",
    image: "https://terrarp.com/db/mastery/w-arcanamancy.png",
    save: "will",
    expertise: "knowledge",
    actions: [
      "Normal Attack",
      "Recover",
      "Rush",
      "Healthy",
      "Alert",
      "Mobile",
      "Auto Assist",
      "Consistent",
      "Risky",
      "Protect",
      "Ultra Protect",
      "Counter",
      "Ultra Counter",
      "Hinder",
      "Ultra Hinder",
      "Taunt",
      "Torment",
      "Alter Hinder",
      "Disruptive",
      "Shield",
      "Overload",
    ],
    role: "defense",
  },
  {
    id: 2,
    lookup: "astramancy",
    name: "Astramancy",
    color: "#ae43c3",
    image: "https://terrarp.com/db/mastery/w-astramancy.png",
    save: "will",
    expertise: "presence",
    actions: [
      "Normal Attack",
      "Recover",
      "Rush",
      "Healthy",
      "Alert",
      "Mobile",
      "Auto Assist",
      "Consistent",
      "Risky",
      "Protect",
      "Ultra Protect",
      "Counter",
      "Ultra Counter",
      "Hinder",
      "Ultra Hinder",
      "Taunt",
      "Torment",
      "Alter Hinder",
      "Disruptive",
      "Shield",
      "Overload",
    ],
    role: "defense",
  },
  {
    id: 1,
    lookup: "beast-arts",
    name: "Beast Arts",
    color: "#db7233",
    image: "https://terrarp.com/db/mastery/w-beast.png",
    save: "reflex",
    expertise: "knack",
    actions: [
      "Normal Attack",
      "Recover",
      "Rush",
      "Healthy",
      "Alert",
      "Mobile",
      "Auto Assist",
      "Consistent",
      "Risky",
      "Protect",
      "Ultra Protect",
      "Counter",
      "Ultra Counter",
      "Hinder",
      "Ultra Hinder",
      "Taunt",
      "Torment",
      "Alter Hinder",
      "Disruptive",
      "Shield",
      "Overload",
    ],
    role: "defense",
  },
  {
    id: 2,
    lookup: "geomancy",
    name: "Geomancy",
    color: "#a76a36",
    image: "https://terrarp.com/db/mastery/w-geomancy.png",
    save: "fortitude",
    expertise: "fitness",
    actions: [
      "Normal Attack",
      "Recover",
      "Rush",
      "Healthy",
      "Alert",
      "Mobile",
      "Auto Assist",
      "Consistent",
      "Risky",
      "Protect",
      "Ultra Protect",
      "Counter",
      "Ultra Counter",
      "Hinder",
      "Ultra Hinder",
      "Taunt",
      "Torment",
      "Alter Hinder",
      "Disruptive",
      "Shield",
      "Overload",
    ],
    role: "defense",
  },
  {
    id: 3,
    lookup: "guard-arts",
    name: "Guard Arts",
    color: "#f2bb36",
    image: "https://terrarp.com/db/mastery/w-guard.png",
    save: "fortitude",
    expertise: "awareness",
    actions: [
      "Normal Attack",
      "Recover",
      "Rush",
      "Healthy",
      "Alert",
      "Mobile",
      "Auto Assist",
      "Consistent",
      "Risky",
      "Protect",
      "Ultra Protect",
      "Counter",
      "Ultra Counter",
      "Hinder",
      "Ultra Hinder",
      "Taunt",
      "Torment",
      "Alter Hinder",
      "Disruptive",
      "Shield",
      "Overload",
    ],
    role: "defense",
  },
  {
    id: 4,
    lookup: "hemomancy",
    name: "Hemomancy",
    color: "#c32222",
    image: "https://terrarp.com/db/mastery/w-hemomancy.png",
    save: "fortitude",
    expertise: "fitness",
    actions: [
      "Normal Attack",
      "Recover",
      "Rush",
      "Healthy",
      "Alert",
      "Mobile",
      "Auto Assist",
      "Consistent",
      "Risky",
      "Protect",
      "Ultra Protect",
      "Counter",
      "Ultra Counter",
      "Hinder",
      "Ultra Hinder",
      "Taunt",
      "Torment",
      "Alter Hinder",
      "Disruptive",
      "Shield",
      "Overload",
    ],
    role: "defense",
  },
  {
    id: 5,
    lookup: "hydromancy",
    name: "Hydromancy",
    color: "#66b8ea",
    image: "https://terrarp.com/db/mastery/w-hydromancy.png",
    save: "will",
    expertise: "knack",
    actions: [
      "Normal Attack",
      "Recover",
      "Rush",
      "Healthy",
      "Alert",
      "Mobile",
      "Auto Assist",
      "Consistent",
      "Risky",
      "Protect",
      "Ultra Protect",
      "Counter",
      "Ultra Counter",
      "Hinder",
      "Ultra Hinder",
      "Taunt",
      "Torment",
      "Alter Hinder",
      "Disruptive",
      "Shield",
      "Overload",
    ],
    role: "defense",
  },
  {
    id: 6,
    lookup: "illusion-magic",
    name: "Illusion Magic",
    color: "#ea5694",
    image: "https://terrarp.com/db/mastery/w-illusion.png",
    save: "will",
    expertise: "presence",
    actions: [
      "Normal Attack",
      "Recover",
      "Rush",
      "Healthy",
      "Alert",
      "Mobile",
      "Auto Assist",
      "Consistent",
      "Risky",
      "Protect",
      "Ultra Protect",
      "Counter",
      "Ultra Counter",
      "Hinder",
      "Ultra Hinder",
      "Taunt",
      "Torment",
      "Alter Hinder",
      "Disruptive",
      "Shield",
      "Overload",
    ],
    role: "defense",
  },
  {
    id: 7,
    lookup: "aeromancy",
    name: "Aeromancy",
    color: "#48d1c3",
    image: "https://terrarp.com/db/mastery/w-aeromancy.png",
    save: "reflex",
    expertise: "knack",
    actions: [
      "Normal Attack",
      "Recover",
      "Rush",
      "Healthy",
      "Alert",
      "Mobile",
      "Auto Assist",
      "Consistent",
      "Risky",
      "Stable Attack",
      "Burst Attack",
      "Sharp Attack",
      "Multi Attack",
      "Sneak Attack",
      "Critical Attack",
      "Wild Attack",
      "Reckless Attack",
      "Duelist",
      "Sharpshooter",
      "Overload",
      "Area Effect",
      "Overload",
      "Disruptive",
    ],
    role: "offense",
  },
  {
    id: 8,
    lookup: "crush-weapons",
    name: "Crush Weapons",
    color: "#ce5e32",
    image: "https://terrarp.com/db/mastery/w-crush.png",
    save: "fortitude",
    expertise: "fitness",
    actions: [
      "Normal Attack",
      "Recover",
      "Rush",
      "Healthy",
      "Alert",
      "Mobile",
      "Auto Assist",
      "Consistent",
      "Risky",
      "Stable Attack",
      "Burst Attack",
      "Sharp Attack",
      "Multi Attack",
      "Sneak Attack",
      "Critical Attack",
      "Wild Attack",
      "Reckless Attack",
      "Duelist",
      "Sharpshooter",
      "Overload",
      "Area Effect",
      "Overload",
      "Disruptive",
    ],
    role: "offense",
  },
  {
    id: 9,
    lookup: "dark-magic",
    name: "Dark Magic",
    color: "#883cca",
    image: "https://terrarp.com/db/mastery/w-dark.png",
    save: "will",
    expertise: "knowledge",
    actions: [
      "Normal Attack",
      "Recover",
      "Rush",
      "Healthy",
      "Alert",
      "Mobile",
      "Auto Assist",
      "Consistent",
      "Risky",
      "Stable Attack",
      "Burst Attack",
      "Sharp Attack",
      "Multi Attack",
      "Sneak Attack",
      "Critical Attack",
      "Wild Attack",
      "Reckless Attack",
      "Duelist",
      "Sharpshooter",
      "Overload",
      "Area Effect",
      "Overload",
      "Disruptive",
    ],
    role: "offense",
  },
  {
    id: 10,
    lookup: "martial-arts",
    name: "Martial Arts",
    color: "#c9c9c9",
    image: "https://terrarp.com/db/mastery/w-martial.png",
    save: "fortitude",
    expertise: "fitness",
    actions: [
      "Normal Attack",
      "Recover",
      "Rush",
      "Healthy",
      "Alert",
      "Mobile",
      "Auto Assist",
      "Consistent",
      "Risky",
      "Stable Attack",
      "Burst Attack",
      "Sharp Attack",
      "Multi Attack",
      "Sneak Attack",
      "Critical Attack",
      "Wild Attack",
      "Reckless Attack",
      "Duelist",
      "Sharpshooter",
      "Overload",
      "Area Effect",
      "Overload",
      "Disruptive",
    ],
    role: "offense",
  },
  {
    id: 11,
    lookup: "pierce-weapons",
    name: "Pierce Weapons",
    color: "#46bcc8",
    image: "https://terrarp.com/db/mastery/w-pierce.png",
    save: "reflex",
    expertise: "knack",
    actions: [
      "Normal Attack",
      "Recover",
      "Rush",
      "Healthy",
      "Alert",
      "Mobile",
      "Auto Assist",
      "Consistent",
      "Risky",
      "Stable Attack",
      "Burst Attack",
      "Sharp Attack",
      "Multi Attack",
      "Sneak Attack",
      "Critical Attack",
      "Wild Attack",
      "Reckless Attack",
      "Duelist",
      "Sharpshooter",
      "Overload",
      "Area Effect",
      "Overload",
      "Disruptive",
    ],
    role: "offense",
  },
  {
    id: 12,
    lookup: "pyromancy",
    name: "Pyromancy",
    color: "#cb3739",
    image: "https://terrarp.com/db/mastery/w-pyromancy.png",
    save: "will",
    expertise: "presence",
    actions: [
      "Normal Attack",
      "Recover",
      "Rush",
      "Healthy",
      "Alert",
      "Mobile",
      "Auto Assist",
      "Consistent",
      "Risky",
      "Stable Attack",
      "Burst Attack",
      "Sharp Attack",
      "Multi Attack",
      "Sneak Attack",
      "Critical Attack",
      "Wild Attack",
      "Reckless Attack",
      "Duelist",
      "Sharpshooter",
      "Overload",
      "Area Effect",
      "Overload",
      "Disruptive",
    ],
    role: "offense",
  },
  {
    id: 13,
    lookup: "ranged-weapons",
    name: "Ranged Weapons",
    color: "#77b933",
    image: "https://terrarp.com/db/mastery/w-ranged.png",
    save: "reflex",
    expertise: "awareness",
    actions: [
      "Normal Attack",
      "Recover",
      "Rush",
      "Healthy",
      "Alert",
      "Mobile",
      "Auto Assist",
      "Consistent",
      "Risky",
      "Stable Attack",
      "Burst Attack",
      "Sharp Attack",
      "Multi Attack",
      "Sneak Attack",
      "Critical Attack",
      "Wild Attack",
      "Reckless Attack",
      "Duelist",
      "Sharpshooter",
      "Overload",
      "Area Effect",
      "Overload",
      "Disruptive",
    ],
    role: "offense",
  },
  {
    id: 14,
    lookup: "shadow-arts",
    name: "Shadow Arts",
    color: "#383838",
    image: "https://terrarp.com/db/mastery/w-shadow.png",
    save: "reflex",
    expertise: "knack",
    actions: [
      "Normal Attack",
      "Recover",
      "Rush",
      "Healthy",
      "Alert",
      "Mobile",
      "Auto Assist",
      "Consistent",
      "Risky",
      "Stable Attack",
      "Burst Attack",
      "Sharp Attack",
      "Multi Attack",
      "Sneak Attack",
      "Critical Attack",
      "Wild Attack",
      "Reckless Attack",
      "Duelist",
      "Sharpshooter",
      "Overload",
      "Area Effect",
      "Overload",
      "Disruptive",
    ],
    role: "offense",
  },
  {
    id: 15,
    lookup: "slash-weapons",
    name: "Slash Weapons",
    color: "#4263cb",
    image: "https://terrarp.com/db/mastery/w-slash.png",
    save: "fortitude",
    expertise: "fitness",
    actions: [
      "Normal Attack",
      "Recover",
      "Rush",
      "Healthy",
      "Alert",
      "Mobile",
      "Auto Assist",
      "Consistent",
      "Risky",
      "Stable Attack",
      "Burst Attack",
      "Sharp Attack",
      "Multi Attack",
      "Sneak Attack",
      "Critical Attack",
      "Wild Attack",
      "Reckless Attack",
      "Duelist",
      "Sharpshooter",
      "Overload",
      "Area Effect",
      "Overload",
      "Disruptive",
    ],
    role: "offense",
  },
  {
    id: 16,
    lookup: "alchemy",
    name: "Alchemy",
    color: "#53b159",
    image: "https://terrarp.com/db/mastery/w-alchemy.png",
    save: "fortitude",
    expertise: "knowledge",
    actions: [
      "Normal Attack",
      "Recover",
      "Rush",
      "Healthy",
      "Alert",
      "Mobile",
      "Auto Assist",
      "Consistent",
      "Risky",
      "Heal",
      "Power Heal",
      "Buff",
      "Power Buff",
      "Inspire",
      "Haste",
      "Revive",
      "Versatile",
      "Overheal",
      "Cure",
      "Boost",
      "Overload",
    ],
    role: "support",
  },
  {
    id: 17,
    lookup: "animancy",
    name: "Animancy",
    color: "#6c319d",
    image: "https://terrarp.com/db/mastery/w-animancy.png",
    save: "will",
    expertise: "knowledge",
    actions: [
      "Normal Attack",
      "Recover",
      "Rush",
      "Healthy",
      "Alert",
      "Mobile",
      "Auto Assist",
      "Consistent",
      "Risky",
      "Heal",
      "Power Heal",
      "Buff",
      "Power Buff",
      "Inspire",
      "Haste",
      "Revive",
      "Versatile",
      "Overheal",
      "Cure",
      "Boost",
      "Overload",
    ],
    role: "support",
  },
  {
    id: 18,
    lookup: "chronomancy",
    name: "Chronomancy",
    color: "#ec4a97",
    image: "https://terrarp.com/db/mastery/w-chronomancy.png",
    save: "reflex",
    expertise: "awareness",
    actions: [
      "Normal Attack",
      "Recover",
      "Rush",
      "Healthy",
      "Alert",
      "Mobile",
      "Auto Assist",
      "Consistent",
      "Risky",
      "Heal",
      "Power Heal",
      "Buff",
      "Power Buff",
      "Inspire",
      "Haste",
      "Revive",
      "Versatile",
      "Overheal",
      "Cure",
      "Boost",
      "Overload",
    ],
    role: "support",
  },
  {
    id: 19,
    lookup: "divine-magic",
    name: "Divine Magic",
    color: "#edb82a",
    image: "https://terrarp.com/db/mastery/w-divine.png",
    save: "will",
    expertise: "presence",
    actions: [
      "Normal Attack",
      "Recover",
      "Rush",
      "Healthy",
      "Alert",
      "Mobile",
      "Auto Assist",
      "Consistent",
      "Risky",
      "Heal",
      "Power Heal",
      "Buff",
      "Power Buff",
      "Inspire",
      "Haste",
      "Revive",
      "Versatile",
      "Overheal",
      "Cure",
      "Boost",
      "Overload",
    ],
    role: "support",
  },
  {
    id: 20,
    lookup: "harmonic-magic",
    name: "Harmonic Magic",
    color: "#36a5e8",
    image: "https://terrarp.com/db/mastery/w-harmonic.png",
    save: "will",
    expertise: "presence",
    actions: [
      "Normal Attack",
      "Recover",
      "Rush",
      "Healthy",
      "Alert",
      "Mobile",
      "Auto Assist",
      "Consistent",
      "Risky",
      "Heal",
      "Power Heal",
      "Buff",
      "Power Buff",
      "Inspire",
      "Haste",
      "Revive",
      "Versatile",
      "Overheal",
      "Cure",
      "Boost",
      "Overload",
    ],
    role: "support",
  },
  {
    id: 21,
    lookup: "magitech",
    name: "Magitech",
    color: "#5c6779",
    image: "https://terrarp.com/db/mastery/w-magitech.png",
    save: "reflex",
    expertise: "knowledge",
    actions: [
      "Normal Attack",
      "Recover",
      "Rush",
      "Healthy",
      "Alert",
      "Mobile",
      "Auto Assist",
      "Consistent",
      "Risky",
      "Heal",
      "Power Heal",
      "Buff",
      "Power Buff",
      "Inspire",
      "Haste",
      "Revive",
      "Versatile",
      "Overheal",
      "Cure",
      "Boost",
      "Overload",
    ],
    role: "support",
  },
  {
    id: 22,
    lookup: "nature-magic",
    name: "Nature Magic",
    color: "#91c023",
    image: "https://terrarp.com/db/mastery/w-nature.png",
    save: "will",
    expertise: "awareness",
    actions: [
      "Normal Attack",
      "Recover",
      "Rush",
      "Healthy",
      "Alert",
      "Mobile",
      "Auto Assist",
      "Consistent",
      "Risky",
      "Heal",
      "Power Heal",
      "Buff",
      "Power Buff",
      "Inspire",
      "Haste",
      "Revive",
      "Versatile",
      "Overheal",
      "Cure",
      "Boost",
      "Overload",
    ],
    role: "support",
  },
  {
    id: 23,
    lookup: "spirit-magic",
    name: "Spirit Magic",
    color: "#50c8cb",
    image: "https://terrarp.com/db/mastery/w-spirit.png",
    save: "will",
    expertise: "awareness",
    actions: [
      "Normal Attack",
      "Recover",
      "Rush",
      "Healthy",
      "Alert",
      "Mobile",
      "Auto Assist",
      "Consistent",
      "Risky",
      "Heal",
      "Power Heal",
      "Buff",
      "Power Buff",
      "Inspire",
      "Haste",
      "Revive",
      "Versatile",
      "Overheal",
      "Cure",
      "Boost",
      "Overload",
    ],
    role: "support",
  },
  {
    id: 24,
    lookup: "aura",
    name: "Aura",
    color: "#e0b439",
    image: "https://terrarp.com/db/mastery/w-aura.png",
    save: "-",
    expertise: "-",
    actions: [
      "Protect",
      "Ultra Protect",
      "Counter",
      "Ultra Counter",
      "Hinder",
      "Ultra Hinder",
      "Taunt",
      "Torment",
      "Alter Hinder",
      "Disruptive",
      "Shield",
      "Overload",
      "Defense",
      "Guardian",
      "Savior",
    ],
    role: "alter",
  },
  {
    id: 25,
    lookup: "battle-spirits",
    name: "Battle Spirits",
    color: "#b72c2c",
    image: "https://terrarp.com/db/mastery/w-battle-spirits.png",
    save: "-",
    expertise: "-",
    actions: [
      "Stable Attack",
      "Burst Attack",
      "Sharp Attack",
      "Multi Attack",
      "Sneak Attack",
      "Critical Attack",
      "Wild Attack",
      "Reckless Attack",
      "Duelist",
      "Sharpshooter",
      "Overload",
      "Area Effect",
      "Overload",
      "Disruptive",
      "Damage",
      "Speed",
      "Berserk",
    ],
    role: "alter",
  },
  {
    id: 26,
    lookup: "corrupt",
    name: "Corrupt",
    color: "#813090",
    image: "https://terrarp.com/db/mastery/w-corrupt.png",
    save: "-",
    expertise: "-",
    actions: [
      "Stable Attack",
      "Burst Attack",
      "Sharp Attack",
      "Multi Attack",
      "Sneak Attack",
      "Critical Attack",
      "Wild Attack",
      "Reckless Attack",
      "Duelist",
      "Sharpshooter",
      "Overload",
      "Area Effect",
      "Overload",
      "Disruptive",
      "Damage",
      "Support",
      "Corruption",
    ],
    role: "alter",
  },
  {
    id: 27,
    lookup: "dynamism",
    name: "Dynamism",
    color: "#87ad3d",
    image: "https://terrarp.com/db/mastery/w-dynamism.png",
    save: "-",
    expertise: "-",
    actions: [
      "Stable Attack",
      "Burst Attack",
      "Sharp Attack",
      "Multi Attack",
      "Sneak Attack",
      "Critical Attack",
      "Wild Attack",
      "Reckless Attack",
      "Duelist",
      "Sharpshooter",
      "Overload",
      "Area Effect",
      "Overload",
      "Disruptive",
      "Speed",
      "Rover",
      "Momentum",
    ],
    role: "alter",
  },
  {
    id: 28,
    lookup: "evoke",
    name: "Evoke",
    color: "#50c8cb",
    image: "https://terrarp.com/db/mastery/w-evoke.png",
    save: "-",
    expertise: "-",
    actions: [
      "Stable Attack",
      "Burst Attack",
      "Sharp Attack",
      "Multi Attack",
      "Sneak Attack",
      "Critical Attack",
      "Wild Attack",
      "Reckless Attack",
      "Duelist",
      "Sharpshooter",
      "Overload",
      "Area Effect",
      "Overload",
      "Disruptive",
      "Damage",
      "Extension",
      "Exceed",
    ],
    role: "alter",
  },
  {
    id: 29,
    lookup: "hyper-sense",
    name: "Hyper Sense",
    color: "#40883a",
    image: "https://terrarp.com/db/mastery/w-hyper-sense.png",
    save: "-",
    expertise: "-",
    actions: [
      "Protect",
      "Ultra Protect",
      "Counter",
      "Ultra Counter",
      "Hinder",
      "Ultra Hinder",
      "Taunt",
      "Torment",
      "Alter Hinder",
      "Disruptive",
      "Shield",
      "Overload",
      "Defense",
      "Extension",
      "Hyper Awareness",
    ],
    role: "alter",
  },
  {
    id: 30,
    lookup: "mend",
    name: "Mend",
    color: "#2f8cc1",
    image: "https://terrarp.com/db/mastery/w-mend.png",
    save: "-",
    expertise: "-",
    actions: [
      "Heal",
      "Power Heal",
      "Buff",
      "Power Buff",
      "Inspire",
      "Haste",
      "Revive",
      "Versatile",
      "Overheal",
      "Cure",
      "Boost",
      "Overload",
      "Support",
      "Infuse",
      "Regeneration",
    ],
    role: "alter",
  },
  {
    id: 31,
    lookup: "metamorph",
    name: "Metamorph",
    color: "#cc4e71",
    image: "https://terrarp.com/db/mastery/w-metamorph.png",
    save: "-",
    expertise: "-",
    actions: [
      "Protect",
      "Ultra Protect",
      "Counter",
      "Ultra Counter",
      "Hinder",
      "Ultra Hinder",
      "Taunt",
      "Torment",
      "Alter Hinder",
      "Disruptive",
      "Shield",
      "Overload",
      "Damage",
      "Defense",
      "Acceleration",
    ],
    role: "alter",
  },
  {
    id: 32,
    lookup: "summon",
    name: "Summon",
    color: "#4a4da5",
    image: "https://terrarp.com/db/mastery/w-summon.png",
    save: "-",
    expertise: "-",
    actions: [
      "Heal",
      "Power Heal",
      "Buff",
      "Power Buff",
      "Inspire",
      "Haste",
      "Revive",
      "Versatile",
      "Overheal",
      "Cure",
      "Boost",
      "Overload",
      "Support",
      "Extension",
      "Coordinate",
    ],
    role: "alter",
  },
  {
    id: 33,
    lookup: "weapon-arts",
    name: "Weapon Arts",
    color: "#cb5050",
    image: "https://terrarp.com/db/mastery/w-weapon-arts.png",
    save: "-",
    expertise: "-",
    actions: [
      "Stable Attack",
      "Burst Attack",
      "Sharp Attack",
      "Multi Attack",
      "Sneak Attack",
      "Critical Attack",
      "Wild Attack",
      "Reckless Attack",
      "Duelist",
      "Sharpshooter",
      "Overload",
      "Area Effect",
      "Overload",
      "Disruptive",
      "Damage",
      "Support",
      "Charge",
    ],
    role: "alter",
  },
];

// Make available globally
window.masterylist = masterylist;
