//
// Version-stamps every local JS/CSS asset URL in the root HTML files so a new
// upload is fetched fresh by browsers and by Cloudflare. Run before every
// upload:  pnpm run stamp
//
// The stamp is the current local time, never a git hash: uncommitted files are
// uploaded too, and a repeated stamp would leave old copies in caches.
"use strict";
const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");

// <script ... src="x.js"> or <link ... href="x.css">, relative only. A URL
// with ":" is absolute (https://) and is left alone. An existing ?v= is
// swallowed so re-running replaces rather than appends.
const ASSET_RE =
    /((?:<script[^>]*\ssrc|<link[^>]*\shref)=")([^"?#:]+\.(?:js|css))(?:\?v=[^"]*)?(")/g;

function makeStamp(date) {
    const d = date || new Date();
    const p = (n) => String(n).padStart(2, "0");
    return `${d.getFullYear()}${p(d.getMonth() + 1)}${p(d.getDate())}-` +
        `${p(d.getHours())}${p(d.getMinutes())}${p(d.getSeconds())}`;
}

function stampHtml(html, stamp) {
    return html.replace(ASSET_RE, (m, head, file, tail) => `${head}${file}?v=${stamp}${tail}`);
}

function htmlFiles() {
    return fs.readdirSync(ROOT)
        .filter((f) => f.endsWith(".html"))
        .map((f) => path.join(ROOT, f));
}

function run(stamp) {
    const s = stamp || makeStamp();
    for (const file of htmlFiles()) {
        const before = fs.readFileSync(file, "utf8");
        const after = stampHtml(before, s);
        if (after !== before) fs.writeFileSync(file, after);
    }
    fs.writeFileSync(path.join(ROOT, "shared", "app-version.js"),
        `// Generated by scripts/stamp-version.js. Do not edit by hand.\nwindow.TS_BUILD = "${s}";\n`);
    fs.writeFileSync(path.join(ROOT, "version.json"), JSON.stringify({ build: s }) + "\n");
    return s;
}

if (require.main === module) {
    const s = run();
    console.log(`Stamped ${htmlFiles().length} HTML files with ${s}`);
}

module.exports = { stampHtml, makeStamp, htmlFiles, run, ASSET_RE, ROOT };
